apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: mzo-app-space
spec:
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
        - image: redis:5.0.4
          imagePullPolicy: Always
          name: redis
          args:
            - redis-server
            - "/redis-master/redis.conf"
          env:
            - name: MASTER
              value: "true"
          resources:
            limits:
              cpu: "0.1"
          ports:
            - containerPort: 6379
              name: "redis"
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
