apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: mzo-ingress-space
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    name: nginx-ingress
