apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: mzo-ingress-space
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  #type: NodePort
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    name: nginx-ingress
