apiVersion: v1
kind: Service
metadata:
  name: video-service # this will allowed the service to be accessed via video-service.mzo-app-space.svc.cluster.local
  namespace: mzo-app-space
spec:
  ports:
    - port: 8080 # this is the port that can be used to reach the service
      protocol: TCP
      targetPort: 8080 # this is the port for reaching the pod: `port` will be mapped to `targetPort`
  selector:
    app: webapp-video
  sessionAffinity: None
  type: ClusterIP
