apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: mzo-app-space
spec:
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - image: hashicorp/http-echo
          imagePullPolicy: Always
          name: echo-server
          args: ["-text='custom reply'", "-listen=:2000"]
          ports:
            - containerPort: 2000
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
