apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: mzo-ingress-space
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: "default"
      targetPort: 80
      nodePort: 30080
    - port: 8080
      name: "http"
      targetPort: 8080
      nodePort: 30081
      protocol: TCP
    - port: 8080
      name: "web-svc"
      targetPort: 8080
      nodePort: 30090
      protocol: TCP
    - port: 1000
      protocol: TCP
      name: "echo-service"
      targetPort: 2000
  selector:
    name: nginx-ingress
