apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: mzo-app-space
spec:
  ports:
    - port: 6379 # port that must be reachable from the ingress resource
      protocol: TCP
      targetPort: 6379 # same as the port that the container is using
  selector:
    app: redis-server
  sessionAffinity: None
  type: ClusterIP
