apiVersion: v1
kind: Service
metadata:
  name: webapp-video-ingress
  namespace: mzo-app-space
spec:
  type: ClusterIP
  ports:
    - name: test
      port: 8080
  selector:
    name: webapp-video # the pods / deployment to point to
