apiVersion: v1
kind: Service
metadata:
  name: wear-service
  namespace: mzo-app-space
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: webapp-wear
  sessionAffinity: None
  type: ClusterIP
